name: live_cells_core
description: > 
  Provides the core of live cells: A replacement for ChangeNotifier and ValueNotifier
  that is easier to use and more flexible
version: 0.18.0
repository: https://github.com/alex-gutev/live_cells/tree/master/live_cells_core
issue_tracker: https://github.com/alex-gutev/live_cells/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ">=1.10.0 <2.0.0"
  collection: ">=1.16.0 <2.0.0"
  live_cell_annotations: ^0.4.0
  record_extender_annotations: ^0.1.0

dev_dependencies:
  test: ^1.25.2
  mockito: ^5.4.4
  fake_async: ^1.3.1
  lints: ^3.0.0
  build_runner: ^2.4.8
  record_extender: ^0.1.0

topics:
  - reactive
  - state-management
  - extension