name: live_cell_annotations
description: "Provides the annotations for use with the live_cells package."
version: 0.4.2
repository: https://github.com/alex-gutev/live_cells/tree/master/live_cell_annotations
issue_tracker: https://github.com/alex-gutev/live_cells/issues

environment:
  sdk: '>=2.18.6 <4.0.0'
