name: live_cells
description: A replacement for ChangeNotifier and ValueNotifier that is easier to use and more flexible
version: 0.25.4
repository: https://github.com/alex-gutev/live_cells/tree/master/live_cells
issue_tracker: https://github.com/alex-gutev/live_cells/issues
homepage: https://livecell.gutev.dev/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  live_cell_annotations: ^0.4.4
  live_cells_core: ^0.24.2
  live_cell_widgets: ^0.12.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=2.0.0'

topics:
  - reactive
  - state-management
  - state-restoration
  - extension
  - ui